### ISSUE TITLE
The app not working

### ISSUE THREAD

**Issue by netshdev** [isarojdahal/Confess-Note#2]
The application does not seem to be working properly. 

Issue:
Confess button - not working
Posting confession - not working
Viewing confession - not working

The website loads, but the confession section is always loading!

![Screen Shot 2022-03-29 at 1 12 57 PM](https://user-images.githubusercontent.com/47726833/160668016-94a3985e-23b8-4be4-ba0d-90c7712441aa.png)

**Comment by isarojdahal** [comment]
Fixed it, brother.
